apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak-ns # Must be in keycloak-ns
  labels:
    app: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090 # NodePort for Keycloak Admin UI (adjust if conflicts)
  type: NodePort
