apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service # Service name for Keycloak to connect to
  namespace: keycloak-ns # Must be in keycloak-ns
  labels:
    app: keycloak-postgres
spec:
  selector:
    app: keycloak-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
