apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-postgres-pv
  labels:
    type: local
    app: keycloak-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/keycloak-postgres"
