apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: dev
  labels:
    app: angular-frontend
spec:
  selector:
    app: angular-frontend
  ports:
    - protocol: TCP
      port: 80         # Port the service exposes (within the cluster)
      targetPort: 80   # Port the Angular container (Nginx) listens on
      nodePort: 30080  # Expose on a high port on the Minikube VM for external access
  type: NodePort       # Accessible from outside the cluster

