apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-dev
  labels:
    type: local
    environment: dev
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi # Allocate 5GB of storage
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  hostPath:
    # This path exists on the Minikube VM.
    # Minikube will create this directory if it doesn't exist.
    path: "/mnt/data/postgres-dev"
