apiVersion: v1
kind: Service
metadata:
  name: postgres-service # This name will be used by Spring Boot to connect
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432       # Port the service exposes (within the cluster)
      targetPort: 5432 # Port the PostgreSQL container listens on
  type: ClusterIP 
