apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service # This name is used by Angular to connect
  labels:
    app: spring-boot-app
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8080       # Port the service exposes within the cluster
      targetPort: 8080 # Port the Spring Boot container listens on
  type: ClusterIP      # Only accessible within the cluster (Angular will connect to this)

