# .github/workflows/deploy.yml
name: Build and Deploy to Kubernetes

# Trigger the workflow on pushes to the 'main' branch
# You can specify paths to only run if relevant code changes
on:
  push:
    branches:
      - main
    paths:
      - 'deployment/**'    # Path to your Spring Boot project
      - 'angular-frontend/**'     # Path to your Angular project
      - 'list deployment file/test/**' # Path to your Kubernetes YAMLs

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Build and Push Spring Boot Image ---
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Spring Boot JAR
      run: |
        # Adjust 'deployment' to your actual Spring Boot project directory name
        cd deployment
        ./mvnw clean package -DskipTests # Skip tests for faster build in pipeline, run them in a separate test job

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Spring Boot Docker image
      run: |
        # Adjust 'deployment' to your actual Spring Boot project directory name
        # Replace 'avinashanandlucky' with your actual Docker Hub username
        # ${{ github.sha }} provides a unique tag based on the commit hash
        cd deployment
        docker build -t avinashanandlucky/test-docker-avinash:${{ github.sha }} .
        docker push avinashanandlucky/spring-boot-service:${{ github.sha }}
        # Also push a 'latest' tag for convenience, but rely on SHA for specific versions
        docker tag avinashanandlucky/test-docker-avinash:${{ github.sha }} avinashanandlucky/test-docker-avinash:latest
        docker push avinashanandlucky/test-docker-avinash:latest


    # --- Build and Push Angular Image ---
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Angular dependencies
      run: |
        # Adjust 'angular-frontend' to your actual Angular project directory name
        cd angular-frontend
        npm install

    - name: Build Angular application
      run: |
        # Adjust 'angular-frontend' to your actual Angular project directory name
        cd angular-frontend
        # Ensure --base-href is correct for your Nginx setup
        npm run build -- --output-path=./dist/angular-frontend --base-href=/

    - name: Build and push Angular Docker image
      run: |
        # Adjust 'angular-frontend' to your actual Angular project directory name
        # Replace 'avinashanandlucky' with your actual Docker Hub username
        cd angular-frontend
        docker build -t avinashanandlucky/test-docker-avinash:${{ github.sha }} .
        docker push avinashanandlucky/test-docker-avinash:${{ github.sha }}
        # Also push a 'latest' tag for convenience
        docker tag avinashanandlucky/test-docker-avinash:${{ github.sha }} avinashanandlucky/test-docker-avinash:latest
        docker push avinashanandlucky/test-docker-avinash:latest

    # --- Manual Deployment Instructions ---
    - name: Provide Manual Deployment Instructions
      run: |
        echo "----------------------------------------------------------------------------------"
        echo "Docker images have been successfully built and pushed to Docker Hub:"
        echo "  - avinashanandlucky/test-docker-avinash:${{ github.sha }}"
        echo "  - avinashanandlucky/test-docker-avinash:${{ github.sha }}"
        echo ""
        echo "To deploy these to your local Minikube cluster (e.g., 'dev' namespace):"
        echo "1. Ensure Minikube is running: 'minikube start'"
        echo "2. Navigate to your list deployment file/test/** directory: 'cd /list deployment file/test/**'"
        echo "3. Update your deployment YAMLs to use the new image tags:"
        echo "   - For springboot-deployment.yaml (in dev/ or test/):"
        echo "     Change 'image: spring-boot-service:backend-dep-v4' to 'image: avinashanandlucky/test-docker-avinash:${{ github.sha }}'"
        echo "   - For angular-frontend-deployment.yaml (in dev/ or test/):"
        echo "     Change 'image: angular-frontend:ui-dep-v10' to 'image: avinashanandlucky/test-docker-avinash:${{ github.sha }}'"
        echo "   (Alternatively, you can just use the 'latest' tag if you're comfortable with that)"
        echo "4. Apply the updated manifests to your desired namespace (e.g., 'dev'):"
        echo "   kubectl apply -f list deployment file/test/**/dev/ # Or specific files"
        echo ""
        echo "Note: For fully automated deployment to a local Minikube, you would typically use a self-hosted GitHub Actions runner on your machine."
        echo "----------------------------------------------------------------------------------"
